### ISSUE TITLE
Redirect to unicode-segmentation crate from unicode-rs

### ISSUE THREAD

**Issue by robinst** [sbillig/rust-grapheme#2]
Looks like this library is no longer maintained and people should be using the [unicode-segmentation](https://crates.io/crates/unicode-segmentation) crate from [unicode-rs](https://unicode-rs.github.io/) instead.

As this repository is still pretty high in Google results (I landed here first), it would be cool if it could have a pointer to the above libraries in its README. In the meantime, this issue might help other people that land here :).

**Comment by canndrew** [comment]
It's @sbillig's library but it looks like he hasn't been online in a long time. I've added the note to the README.

**Comment by sbillig** [comment]
Thanks @robinst and @canndrew.
